### ISSUE TITLE
Problem with demoIonicStart

### ISSUE THREAD

**Issue by andrewead** [GetMati/mati-cordova-plugin#2]
I'm having this error when I'm trying to install or update the sdk:

cordova plugin add https://github.com/GetMati/mati-cordova-plugin.git
Failed to fetch plugin https://github.com/GetMati/mati-cordova-plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'EXAMPLES/demoIonicStart' in .gitmodules
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrew/.npm/_logs/2021-04-23T18_30_30_965Z-debug.log

You have to delete this folder demoIonicStart

**Comment by aposnovmati** [comment]
@andrewead Hello! done, please try again, thanks a lot for your help

**Comment by aposnovmati** [comment]
@andrewead  Hello, please try our latest plugin version 2.0.2
