### ISSUE TITLE
Reference to MatiSDK.h

### ISSUE THREAD

**Issue by andrewead** [GetMati/mati-cordova-plugin#3]
The MatiSDK.h import reference from MatiSDK.m is apparently broken.

![MatiSDK m 2021-04-28 13-30-57](https://user-images.githubusercontent.com/70617931/116455097-4c76a680-a826-11eb-9e4f-8ecac66aaf12.png)

**Comment by aposnovmati** [comment]
Hello @andrewead we didnt found any problems, did you follow instructions? Did you tried our examples?

**Comment by aposnovmati** [comment]
@andrewead  Hello, please try our latest plugin version 2.0.2
