### ISSUE TITLE
setMatiCallback

### ISSUE THREAD

**Issue by luizpaulobra** [GetMati/mati-cordova-plugin#4]
Hello, I tried the integration with Cordova from demo app and my own app, but have no callback after succeffuly finish all documents validation process, this is expected or exists another solution for that? Thanks

**Comment by kmilo291** [comment]
Hello, I have the same problem since the library update, the callbacks are not responding when I finish with success or error

**Comment by aposnovmati** [comment]
@luizpaulobra @kmilo291   Hello, please try our latest plugin version 2.0.2
