### ISSUE TITLE
java.lang.RuntimeException: Please use Mati button inside AppCompatActivity

### ISSUE THREAD

**Issue by gcfederico** [GetMati/mati-cordova-plugin#5]
![image](https://user-images.githubusercontent.com/12576016/119591566-36202400-bdad-11eb-8117-9bbe92aabd17.png)

Hello,

I get this error every time I call showMatiFlow() from an ordinary <ion-button> in a ionic page componente in android plarform.

I leave here some, dependencies versions as context information:

`"@ionic/angular": "^4.11.13",`
`"@angular/core": "^7.2.2",`
`"cordova-android": "^9.1.0",`

**Comment by aposnovmati** [comment]
Hello @gcfederico you missed important step on n documentation, please take a look https://github.com/GetMati/mati-cordova-plugin/blob/master/README.md calls Please change public class CordovaActivity.java

**Comment by aposnovmati** [comment]
@luizpaulobra @kmilo291   Hello, please try our latest plugin version 2.0.2
