### ISSUE TITLE
 mati stuck when loading document images in IOS

### ISSUE THREAD

**Issue by kmilo291** [GetMati/mati-cordova-plugin#6]
Hello, when the images of the documents are being loaded for the validation process, the application stays loading and the process never ends, this only happens in IOS. Thank you for your help with this situation.

**Comment by aposnovmati** [comment]
@kmilo291 Hello, thank you, we will check it and return to you tomorrow

**Comment by aposnovmati** [comment]
@kmilo291 Hello, please try our latest plugin version 2.0.2
