### ISSUE TITLE
Error installing the plugin in ionic

### ISSUE THREAD

**Issue by marronedamian** [GetMati/mati-cordova-plugin#7]
When trying to install the plugin in my project it returns the following error

![Pasted Image_ Jun 11, 2021 - 1_00_42pm](https://user-images.githubusercontent.com/17587930/121901364-b70f7300-ccfc-11eb-98df-e7d8f6f5039b.png)

Could you help me with this @aposnovmati @aposnov  ?
Thank you

**Comment by marronedamian** [comment]
> When trying to install the plugin in my project it returns the following error
> 
> ![Pasted Image_ Jun 11, 2021 - 1_00_42pm](https://user-images.githubusercontent.com/17587930/121901364-b70f7300-ccfc-11eb-98df-e7d8f6f5039b.png)
> 
> Could you help me with this @aposnovmati @aposnov ?
> Thank you

In the following way he installed it but I do not know if it is the correct way.

npm install https://github.com/GetMati/mati-cordova-plugin.git --save  

![mati_ionic](https://user-images.githubusercontent.com/17587930/121908144-153f5480-cd03-11eb-8b83-460d9847b6a6.PNG)

**Comment by aposnovmati** [comment]
@marronedamian hello, both ways is same)

**Comment by marronedamian** [comment]
Hello, @aposnovmati  ! thanks for answering  , after installing your plugin and trying to compile I get the following error that did not happen before.

![mati_ionic_error](https://user-images.githubusercontent.com/17587930/121915421-93065e80-cd09-11eb-9e5e-2cbe6d3a9f39.PNG)

**Comment by marronedamian** [comment]
Ionic:

   Ionic CLI          : 5.4.16 (C:\Users\Damian\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.6
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.1, (and 21 other plugins)

**Comment by aposnovmati** [comment]
Hello @marronedamian please run with --info or --debug flags to get more log output

**Comment by marronedamian** [comment]
Hi @aposnovmati ! In both cases it returns the following: 

`√ Browser application bundle generation complete.
√ ES5 bundle generation complete.
√ Copying assets complete.
√ Index html generation complete.

Initial Chunk Files                 | Names                     |      Size
vendor-es5.js                       | vendor                    |   5.66 MB
vendor-es2015.js                    | vendor                    |   4.61 MB
polyfills-es5.js                    | polyfills-es5             | 681.33 kB
polyfills-es2015.js                 | polyfills                 | 257.33 kB
cordova.js                          | cordova                   |  63.62 kB
styles.css                          | styles                    |  32.58 kB
main-es5.js                         | main                      |  15.18 kB
main-es2015.js                      | main                      |  13.27 kB
runtime-es2015.js                   | runtime                   |   9.54 kB
runtime-es5.js                      | runtime                   |   9.54 kB

                                    | Initial ES5 Total         |   6.44 MB
                                    | Initial ES2015 Total      |   4.98 MB

Lazy Chunk Files                    | Names                     |      Size
swiper-bundle-95afeea2-js-es5.js    | swiper-bundle-95afeea2-js | 249.50 kB
swiper-bundle-95afeea2-js-es2015.js | swiper-bundle-95afeea2-js | 206.34 kB
polyfills-core-js-es5.js            | polyfills-core-js         | 188.47 kB
11-es5.js                           | -                         |  98.80 kB
2-es5.js                            | -                         |  93.79 kB
polyfills-core-js-es2015.js         | polyfills-core-js         |  92.36 kB
17-es5.js                           | -                         |  82.37 kB
33-es5.js                           | -                         |  79.71 kB
11-es2015.js                        | -                         |  74.07 kB
17-es2015.js                        | -                         |  72.71 kB
26-es5.js                           | -                         |  71.45 kB
2-es2015.js                         | -                         |  64.42 kB
1-es5.js                            | -                         |  58.56 kB
33-es2015.js                        | -                         |  56.82 kB
29-es5.js                           | -                         |  56.74 kB
21-es5.js                           | -                         |  56.23 kB
19-es5.js                           | -                         |  50.31 kB
31-es5.js                           | -                         |  48.54 kB
1-es2015.js                         | -                         |  48.04 kB
26-es2015.js                        | -                         |  47.95 kB
16-es5.js                           | -                         |  45.79 kB
30-es5.js                           | -                         |  40.23 kB
32-es5.js                           | -                         |  38.63 kB
6-es5.js                            | -                         |  38.26 kB
31-es2015.js                        | -                         |  37.54 kB
0-es5.js                            | -                         |  37.21 kB
20-es5.js                           | -                         |  36.12 kB
25-es5.js                           | -                         |  34.73 kB
21-es2015.js                        | -                         |  33.38 kB
30-es2015.js                        | -                         |  33.31 kB
polyfills-dom-es5.js                | polyfills-dom             |  33.15 kB
19-es2015.js                        | -                         |  32.69 kB
6-es2015.js                         | -                         |  32.60 kB
12-es5.js                           | -                         |  32.19 kB
16-es2015.js                        | -                         |  31.57 kB
42-es5.js                           | -                         |  30.11 kB
0-es2015.js                         | -                         |  30.06 kB
40-es5.js                           | -                         |  30.04 kB
36-es5.js                           | -                         |  28.22 kB
22-es5.js                           | -                         |  27.68 kB
15-es5.js                           | -                         |  27.28 kB
20-es2015.js                        | -                         |  27.15 kB
25-es2015.js                        | -                         |  26.69 kB
12-es2015.js                        | -                         |  26.61 kB
24-es5.js                           | -                         |  25.23 kB
32-es2015.js                        | -                         |  25.01 kB
39-es5.js                           | -                         |  24.99 kB
29-es2015.js                        | -                         |  24.52 kB
23-es5.js                           | -                         |  24.32 kB
36-es2015.js                        | -                         |  24.09 kB
input-shims-7ec33d9a-js-es5.js      | input-shims-7ec33d9a-js   |  22.88 kB
41-es5.js                           | -                         |  22.77 kB
40-es2015.js                        | -                         |  22.02 kB
23-es2015.js                        | -                         |  22.01 kB
22-es2015.js                        | -                         |  21.41 kB
15-es2015.js                        | -                         |  20.78 kB
10-es5.js                           | -                         |  20.52 kB
4-es5.js                            | -                         |  20.40 kB
18-es5.js                           | -                         |  19.98 kB
common-es5.js                       | common                    |  19.90 kB
14-es5.js                           | -                         |  19.76 kB
polyfills-dom-es2015.js             | polyfills-dom             |  19.55 kB
shadow-css-23c95dd7-js-es5.js       | shadow-css-23c95dd7-js    |  19.48 kB
7-es5.js                            | -                         |  19.47 kB
27-es5.js                           | -                         |  19.08 kB
37-es5.js                           | -                         |  18.59 kB
39-es2015.js                        | -                         |  18.56 kB
42-es2015.js                        | -                         |  18.46 kB
41-es2015.js                        | -                         |  17.11 kB
shadow-css-23c95dd7-js-es2015.js    | shadow-css-23c95dd7-js    |  16.20 kB
7-es2015.js                         | -                         |  16.11 kB
24-es2015.js                        | -                         |  16.04 kB
4-es2015.js                         | -                         |  15.86 kB
10-es2015.js                        | -                         |  15.85 kB
input-shims-7ec33d9a-js-es2015.js   | input-shims-7ec33d9a-js   |  15.79 kB
polyfills-css-shim-es5.js           | polyfills-css-shim        |  15.70 kB
18-es2015.js                        | -                         |  15.31 kB
8-es5.js                            | -                         |  14.93 kB
common-es2015.js                    | common                    |  13.56 kB
14-es2015.js                        | -                         |  13.20 kB
27-es2015.js                        | -                         |  12.34 kB
35-es5.js                           | -                         |  12.11 kB
8-es2015.js                         | -                         |  11.55 kB
9-es5.js                            | -                         |  11.26 kB
polyfills-css-shim-es2015.js        | polyfills-css-shim        |  10.68 kB
home-home-module-es5.js             | home-home-module          |  10.30 kB
34-es5.js                           | -                         |   9.86 kB
28-es5.js                           | -                         |   9.81 kB
9-es2015.js                         | -                         |   9.78 kB
35-es2015.js                        | -                         |   9.43 kB
home-home-module-es2015.js          | home-home-module          |   8.35 kB
37-es2015.js                        | -                         |   8.01 kB
34-es2015.js                        | -                         |   7.92 kB
3-es5.js                            | -                         |   7.85 kB
keyboard-5742b5da-js-es5.js         | keyboard-5742b5da-js      |   7.48 kB
tap-click-cc1ae2b2-js-es5.js        | tap-click-cc1ae2b2-js     |   6.97 kB
keyboard-5742b5da-js-es2015.js      | keyboard-5742b5da-js      |   6.10 kB
28-es2015.js                        | -                         |   6.07 kB
3-es2015.js                         | -                         |   5.94 kB
tap-click-cc1ae2b2-js-es2015.js     | tap-click-cc1ae2b2-js     |   5.70 kB
13-es5.js                           | -                         |   5.33 kB
5-es5.js                            | -                         |   5.31 kB
5-es2015.js                         | -                         |   3.40 kB
13-es2015.js                        | -                         |   3.31 kB
swipe-back-7ed48517-js-es5.js       | swipe-back-7ed48517-js    |   3.20 kB
38-es5.js                           | -                         |   2.97 kB
swipe-back-7ed48517-js-es2015.js    | swipe-back-7ed48517-js    |   2.74 kB
focus-visible-f4ad4f1a-js-es5.js    | focus-visible-f4ad4f1a-js |   2.42 kB
status-tap-3a499f55-js-es5.js       | status-tap-3a499f55-js    |   2.02 kB
focus-visible-f4ad4f1a-js-es2015.js | focus-visible-f4ad4f1a-js |   1.97 kB
38-es2015.js                        | -                         |   1.66 kB
status-tap-3a499f55-js-es2015.js    | status-tap-3a499f55-js    |   1.65 kB

Build at: 2021-06-18T14:36:55.027Z - Hash: 0a24d45922754c2aacdd - Time: 11472ms
> cordova.cmd build android --debug
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=C:\Users\Damian\AppData\Local\Android\Sdk (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: C:\Users\Damian\AppData\Local\Android\Sdk
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:checkDebugAarMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.constraintlayout:constraintlayout-solver:2.0.4, androidx.versionedparcelable:versionedparcelable:1.1.0, androidx.appcompat:appcompat:1.2.0, androidx.lifecycle:lifecycle-common-java8:2.2.0, androidx.customview:customview:1.1.0, androidx.exifinterface:exifinterface:1.0.0, com.google.android.material:material:1.3.0, androidx.fragment:fragment-ktx:1.3.0, androidx.compose.ui:ui-graphics:1.0.0-beta02, androidx.viewpager2:viewpager2:1.0.0, androidx.cardview:cardview:1.0.0, androidx.navigation:navigation-compose:1.0.0-alpha09, androidx.navigation:navigation-runtime:2.3.4, androidx.savedstate:savedstate:1.1.0, androidx.camera:camera-view:1.0.0-alpha24, androidx.lifecycle:lifecycle-process:2.2.0, androidx.lifecycle:lifecycle-runtime-ktx:2.3.0, androidx.lifecycle:lifecycle-common:2.3.0, androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.0, androidx.compose.animation:animation-core:1.0.0-beta02, androidx.lifecycle:lifecycle-viewmodel:2.3.0, androidx.navigation:navigation-fragment-ktx:2.3.4, androidx.navigation:navigation-dynamic-features-fragment:2.3.4, androidx.savedstate:savedstate-ktx:1.1.0, androidx.activity:activity:1.3.0-alpha04, androidx.annotation:annotation-experimental:1.1.0-rc01, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.dynamicanimation:dynamicanimation:1.0.0, androidx.recyclerview:recyclerview:1.1.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.activity:activity-compose:1.3.0-alpha04, androidx.coordinatorlayout:coordinatorlayout:1.1.0, androidx.transition:transition:1.3.0, androidx.print:print:1.0.0, androidx.navigation:navigation-fragment:2.3.4, androidx.compose.runtime:runtime-saveable:1.0.0-beta02, androidx.fragment:fragment:1.3.0, androidx.navigation:navigation-runtime-ktx:2.3.4, androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.0, androidx.interpolator:interpolator:1.0.0, androidx.compose.ui:ui-unit:1.0.0-beta02, androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha03, androidx.loader:loader:1.0.0, androidx.navigation:navigation-ui-ktx:2.3.4, androidx.compose.ui:ui-text:1.0.0-beta02, androidx.collection:collection:1.1.0, androidx.viewpager:viewpager:1.0.0, androidx.drawerlayout:drawerlayout:1.1.1, androidx.core:core:1.5.0-beta01, androidx.lifecycle:lifecycle-livedata-core-ktx:2.3.0, androidx.constraintlayout:constraintlayout:2.0.4, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.arch.core:core-common:2.1.0, androidx.camera:camera-camera2:1.0.0, androidx.collection:collection-ktx:1.1.0, androidx.annotation:annotation:1.2.0-beta01, androidx.core:core-ktx:1.3.2, androidx.appcompat:appcompat-resources:1.2.0, androidx.concurrent:concurrent-futures:1.0.0, androidx.navigation:navigation-common:2.3.4, androidx.autofill:autofill:1.0.0, androidx.lifecycle:lifecycle-livedata:2.1.0, androidx.activity:activity-ktx:1.3.0-alpha04, androidx.tracing:tracing:1.0.0, androidx.navigation:navigation-dynamic-features-runtime:2.3.4, androidx.compose.runtime:runtime:1.0.0-beta02, androidx.compose.ui:ui-util:1.0.0-beta02, androidx.camera:camera-lifecycle:1.0.0, androidx.arch.core:core-runtime:2.1.0, androidx.documentfile:documentfile:1.0.0, androidx.compose.ui:ui:1.0.0-beta02, androidx.lifecycle:lifecycle-livedata-core:2.3.0, androidx.navigation:navigation-ui:2.3.4, androidx.vectordrawable:vectordrawable-animated:1.1.0, androidx.camera:camera-core:1.0.0, androidx.compose.ui:ui-geometry:1.0.0-beta02, androidx.vectordrawable:vectordrawable:1.1.0, androidx.lifecycle:lifecycle-runtime:2.3.0, androidx.navigation:navigation-common-ktx:2.3.4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
4 actionable tasks: 1 executed, 3 up-to-date
Command failed with exit code 1: c:\xampp\htdocs\aplicaciones\mati-mobile-examples\cordovaIonicDemoApp\platforms\android\gradlew cdvBuildDebug -b c:\xampp\htdocs\aplicaciones\mati-mobile-examples\cordovaIonicDemoApp\platforms\android\build.gradle
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android --debug exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.`

**Comment by aposnovmati** [comment]
Hello @marronedamian is it actual?  do you manage to resolve it?

**Comment by aposnovmati** [comment]
Hello, @marronedamian is it works now? was there an issue in the environment?

**Comment by aposnovmati** [comment]
if you will have more questions/issues please open new ticket
